### ISSUE TITLE
Ads not working

### ISSUE THREAD

**Issue by netset-code** [devalentino/prebid-mobile-react-native#5] opened 2019-08-22 13:07 UTC
![Screenshot from 2019-08-22 18-37-18](https://user-images.githubusercontent.com/54404558/63517075-e3e10d80-c50b-11e9-8bca-8ae37dae9130.png)

**Comment by netset-code** [comment] 2019-08-22 13:09
Hi
I need help to add premid in react native app.I had implemented your code in my app but unable to get any ad and in callback response 'errors:
PREBID_SERVER_ADAPTER: "PREBID_SERVER_ADAPTER: request build timeout"

**Comment by netset-code** [comment] 2019-08-27 07:07
@devalentino

**Comment by devalentino** [comment] 2019-08-27 09:07
Hi. Sorry, I wasn't aware someone uses it. Didn't work on this lib for almost 2y. Not sure everything is still working.
From demo I see you should init `PrebidServerAdapter` with `accountId` and timeout. Also you should have valid `configId`. In demo I have `config.js` file with the following configuration:
```javascript
export const accountId='********-****-****-****-************';
export const configId='********-****-****-****-************';
```

I'll try to take a look later today

**Comment by netset-code** [comment] 2019-08-27 09:49
Hi @devalentino 
Thanks for the reply...yes I had used ConfigId and AccountId but result always shown as in above screenshot. I am really in need of this.Your help will be apreciated.

**Comment by devalentino** [comment] 2019-08-27 17:41
The issue is `NetInfo` imported from `react-native`, however it was moved to separate package. 
I played a little with freshly created react native app and got response from server (however I am not valid user there).

The thing is `NetInfo`, `CarrierInfo`, `geolocation` fails and future's `resolve` is newer called https://github.com/devalentino/prebid-mobile-react-native-demo/blob/master/src/index.js#L94 and `PrebidServerAdapter` fails with timeout.

will update demo for latest libraries versions once I have time
 
![image](https://user-images.githubusercontent.com/939104/63794158-04450980-c90a-11e9-9637-4d50ffffc8ff.png)

**Comment by netset-code** [comment] 2019-08-28 07:00
Thank you for the help.
I resolved the geolocation ..and it is working now but I didn't get any ad yet.Is there any problem with my Config id?
![Screenshot from 2019-08-28 12-28-19](https://user-images.githubusercontent.com/54404558/63832993-93e0cb80-c98f-11e9-9109-e93b54fff8d1.png)

**Comment by netset-code** [comment] 2019-08-28 07:01
![Screenshot from 2019-08-28 12-31-16](https://user-images.githubusercontent.com/54404558/63833090-c38fd380-c98f-11e9-97e0-4648f09e6c71.png)

**Comment by devalentino** [comment] 2019-08-28 07:51
This is question for AppNexus. I guess you should sign contract with them first.

**Comment by netset-code** [comment] 2019-08-28 08:01
So it is working on our side..I mean the banner will display if I put correct Confid id?

**Comment by devalentino** [comment] 2019-08-28 08:51
you should receive response with banner in `auction.result.PREBID_SERVER_ADAPTER`. As far as I remember, it will be object with price, url and some other attributes (response structure should be described in AppNexus documentation).
You also need to have some place it your app where banner is displaying. So you need to have something like `<Image source={{ uri: auction.result.PREBID_SERVER_ADAPTER[0].url }} />` in order to display banner in your app

**Comment by netset-code** [comment] 2019-08-28 13:06
but there is no any PREBID_SERVER_ADAPTER[0].url url in my response.

**Comment by devalentino** [comment] 2019-08-28 14:04
I am not sure it is exact `url`. Once you have contract with AppNexus and they started buying your traffic - you get appropriate response with creatives and you can display them in your app

**Comment by devalentino** [comment] 2019-08-28 14:14
Maybe AppNexus could provide you sandbox for testing and you can play with their creatives before traffic selling is started.
Library sends requests and provides responses. If you have no bids, it doesn't mean library works wrong. It could be requirement for contract, or AppNexus don't want to buy your traffic or something else.

**Comment by netset-code** [comment] 2019-08-29 05:15
Okay Thank you...I will contact to Appnexus .

**Comment by netset-code** [comment] 2019-08-30 04:52
Hi @devalentino 
I got the url in response now.Can you please help me how to show that url in app.js file in image tag because it comes under script tag and in index.js file .

**Comment by devalentino** [comment] 2019-08-30 07:35
I am glad to hear you got response from exchange. It means library works as expected.
However showing ads in your app is out of scope of this library. I don't think `prebid-mobile-react-native` issue is correct place to discuss details of your project. If you want to get my consultation, please send me personal email.

**Closed as completed by devalentino** 2019-08-30 07:35 UTC

**Comment by netset-code** [comment] 2019-08-30 12:45
Okay thank you...I will send you an email regarding this.
